text= str("congratulation")
word= input("enter the word in lowercase:")
uppercase_word= word.upper()
print("uppercase_word:", uppercase_word)
word= input("enter the word in uppercase:")
lowercase_word= word.lower()
print("lowercase_word:", lowercase_word)
